version: '3'
services:
  functions:
    build:
      context: .
      dockerfile: ./.devcontainer/functions/Dockerfile
      args:
        VARIANT: 14
    image: functions
    ports:
      - "7071:7071"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    networks:
      - frontend
      - backend
    depends_on:
      - cosmos-db-emulator

  cosmos-db-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports: 
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
      # AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: # Direct mode を利用する場合に必要
    # # 現状の Codespaces では適用されない
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 3g
    networks: 
      - backend

networks:
  frontend:
  backend:
